ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add_to_cart/<int:id>',views.add_to_cart,name='add_to_cart'),
    path('cart_views',views.cart_views,name='cart_views'),
    path('cart_remove/<int:id>',views.cart_remove,name='cart_remove'),
    path('cart_trash/<int:id>/<int:c_id>',views.cart_trash,name='cart_trash'),
    path('place_order/',views.place_order,name='place_order'),
    path('status/<u>',views.status,name='status'),
    path('your_orders',views.your_orders,name='your_orders'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls')),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='search'

urlpatterns = [
    path('search_products/', views.search_products, name='search_products'),
]

ecommerce/shop/urls.py
from django.urls import path
from . import views
app_name='shop'
urlpatterns = [
    path('',views.home,name='home'),
    path('category/', views.category, name='category'),
    path('products/<int:id>', views.products, name='products'),
    path('product_details/<int:id>',views.product_details,name='product_details'),
    path('register/',views.register,name='register'),
    path('user_login',views.user_login,name='user_login'),
    path('user_logout',views.user_logout,name='user_logout'),
    path('buy/<int:id>',views.buy,name='buy'),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

# Create your models here.

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    data_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.quantity*self.product.price

    def __str__(self):
        return self.product.name

class Order_table(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    phone=models.CharField(max_length=12)
    address=models.TextField()
    pin=models.CharField(max_length=30)
    orderd_date=models.DateTimeField(auto_now_add=True)
    order_id=models.CharField(max_length=100,blank=True)
    payment_status=models.CharField(default="pending",max_length=30)
    delivery_status=models.CharField(default='pending',max_length=30)

    def __str__(self):
        return self.user.username

class Payment(models.Model):
    name=models.CharField(max_length=100)
    amount=models.CharField(max_length=100)
    order_id=models.CharField(max_length=100,blank=True)
    razorpay_payment_id=models.CharField(max_length=100,blank=True)
    paid=models.BooleanField(default=False)

    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.contrib.auth.models import User
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from . models import Cart,Payment,Order_table
from shop.models import Product
from django.contrib.auth.decorators import login_required
import razorpay
from django.contrib.auth import login

# Create your views here.

@login_required
def add_to_cart(request,id):
    p=Product.objects.get(id=id)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(p.stock>0):
            cart.quantity += 1
            cart.save()
            p.stock -= 1
            p.save()
    except:
        if(p.stock):
            cart=Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
            p.stock -= 1
            p.save()
    return redirect('cart:cart_views')

@login_required
def cart_views(request):
    u=request.user
    cart=Cart.objects.filter(user=u)
    total=0
    for i in cart:
        total=total+i.quantity*i.product.price
    return render(request,'cart.html',{'cart':cart,'total':total})

def cart_remove(request,id):
    p = Product.objects.get(id=id)
    u = request.user
    # cart = Cart.objects.get(user=u, product=p)
    # cart.quantity -= 1
    # cart.save()
    # p.stock += 1
    # p.save()
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(cart.quantity>1):
            cart.quantity -=1
            cart.save()
            p.stock +=1
            p.save()
        else:
            cart.delete()
            p.stock +=1
            p.save()
    except:
        pass
    return redirect('cart:cart_views')

def cart_trash(request,id,c_id):
    user=request.user
    p=Product.objects.get(id=id)
    cart=Cart.objects.get(user=user,product=p)
    q=cart.quantity
    p.stock=p.stock+q
    p.save()
    c=Cart.objects.get(id=c_id)
    c.delete()
    return redirect('cart:cart_views')

# can also pass 1 id. refer below code
# def cart_trash(request,id):
#     p=Product.objects.get(id=id)
#     u=request.user
#     try:
#         cart=Cart.objects.get(user=u,product=p)
#         cart.delete()
#         p.stock=p.stock+cart.quantity
#         p.stock()
#     except:
#         pass
#     return redirect('cart:cart_views')

def place_order(request):
    if(request.method=='POST'):
        ph=request.POST.get('p')
        a=request.POST.get('a')
        n=request.POST.get('n')
        u=request.user
        c=Cart.objects.filter(user=u)   #cart for current user
        total=0
        for i in c:
            total=total+(i.quantity*i.product.price)    #to get total amount
        total=int(total*100)

        #create Razorpay client using our API credentials
                                          #keyid                      #secretkey
        client=razorpay.Client(auth=('rzp_test_IeuNEvE2rTYxQD','sqsdZCinYPjhr7qnW5dm26li'))

        #Create order in Razorpay
        response_payment=client.order.create(dict(amount=total,currency='INR'))
        print(response_payment)
        order_id=response_payment['id']     #retrive the order_id returned from razorpay response
        order_status=response_payment['status']     #retrive the status returned from razorpay response
        if order_status=="created":     #if status is order created then we save order id in payment table
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()
            for i in c:
                o=Order_table.objects.create(user=u,product=i.product,address=a,phone=ph,pin=n,no_of_items=i.quantity,order_id=order_id)
                o.save()
        response_payment['name']=u.username
        return render(request,'payment.html',{'payment':response_payment})
    return render(request,'place_order.html')

@csrf_exempt        #if csrf related error should not come while running
def status(request,u):
    print(request.user.is_authenticated)    #it should be false
    if not request.user.is_authenticated:   #this 3 lines is for making it in log_in page itself after payment. Coz before it was loggin_out after payment
        u = User.objects.get(username=u)
        login(request,u)
        print(u.is_authenticated)   #when it is true
    if(request.method=="POST"):
        response=request.POST          #Razorpay response after completion of payment
        print(response)
        print(u)
        param_dict={
            'razorpay_order_id':response['razorpay_order_id'],      #this cam from terminal after print(response) is given
            'razorpay_payment_id':response['razorpay_payment_id'],
            'razorpay_signature':response['razorpay_signature']
        }
        client = razorpay.Client(auth=('rzp_test_IeuNEvE2rTYxQD', 'sqsdZCinYPjhr7qnW5dm26li'))
        try:
            status=client.utility.verify_payment_signature(param_dict)  #to check the authentication of razorpay signature
            print(status)
            #retrive a payment record with particular order_id
            ord=Payment.objects.get(order_id=response['razorpay_order_id'])
            ord.razorpay_payment_id=response['razorpay_payment_id'] #edits payment id response['razorpay_payment_id']
            ord.paid=True   #edit to paid
            ord.save()

            u=User.objects.get(username=u)
            c=Cart.objects.filter(user=u)
            #filter the order_table details for particular user with order_id=response['razorpay_order_id']
            o=Order_table.objects.filter(user=u,order_id=response['razorpay_order_id'])
            for i in o:
                i.payment_status="paid" #edit payment_status="paid"
                i.save()
            c.delete()
            return render(request,'status.html',{'status':True})
        except:
            return render(request,'status.html',{'status':False})
    return render(request,'status.html')

@login_required
def your_orders(request):
    u=request.user
    customer=Order_table.objects.filter(user=u,payment_status="paid")
    return render(request,'your_orders.html',{'customer':customer,'u':u.username})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Title</title>


    {% block title %}
    {% endblock %}

</head>
<body>
<center>

<img src="{% static 'images/mintra.jpg' %}" height="50px" width="50px">

</center>

<!-- navbar-->

<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-light bg-light">
  <div class="container-fluid">
      <i class="fa-solid fa-cart-shopping"></i>
    <a class="navbar-brand" href="#">My Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:home' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="{% url 'shop:category' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
            <ul class="dropdown-menu">
              {% for i in links %}
                <li><a class="dropdown-item" href="{% url 'shop:products' i.id %}">{{i.cname}}</a></li>
              {% endfor %}
            </ul>
        </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'cart:your_orders' %}">Your orders</a>
        </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'shop:user_logout' %}">Logout</a>
        </li>

      </ul>

        <a href="{% url 'cart:cart_views' %}"><i class="fa-solid fa-cart-shopping" ></i></a><sup>{{count}}</sup>

      <form class="d-flex" role="search" method="post" action="{% url 'search:search_products' %}">
            {% csrf_token %}
            <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

          {% else %}

          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:user_login' %}">Login</a>
        </li>
          {% endif %}



    </div>
  </div>
</nav>

    {% block content %}



    {% endblock %}


<!--footer-->

<footer class="footer">

        <div class="col text-center">
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://www.myntra.com/" target="_blank">Shopping</a>
        </div>
</footer>

</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
	.btn1
	{
		background-color: white;
		padding:10px;
		color: #000;
		font-weight: bold;
		border: 1px solid red;
		border-radius:30px;
		text-decoration:none;
	}
	.btn1:hower
	{
	}
</style>

<br>

<center>
<h5>Shopping Cart</h5>
</center>

<br>

<div>
	<div class="row">
		<div class="col-6">
			<table class="table table-boarded">
				<tr>
					<th>Cart Items</th>
				</tr>
				{% for i in cart %}
				<tr>
					<td><img src="{{i.product.image.url}}" height="100px"></td>
					<td>Product Name:{{i.product.name}}</td>
					<td>Product Id:{{i.product.id}}</td>
					<td>Quantity:{{i.quantity}}</td>
					<td>Unit Price:{{i.product.price}}*{{i.quantity}}</td>
					<td>Subtotal:{{i.subtotal}}</td>
					<td>
						{% if i.product.stock > 0 %}
						<a href="{% url 'cart:add_to_cart' i.product.id %}"><i class="fa-solid fa-plus"></i></a> <br>
						<a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-minus"></i></a> <br>
						<a href="{% url 'cart:cart_trash' i.product.id i.id %}"><i class="fa-solid fa-trash"></i></a>
						{% else %}
						<a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-minus"></i></a> <br>
						<a href="{% url 'cart:cart_trash' i.product.id i.id %}"><i class="fa-solid fa-trash"></i></a>
						{% endif %}
					</td>
				</tr>
				{% endfor %}
			</table>
		</div>

		<div class="col-6">
			<table class="table table-boarded">
				<tr>
					<th>CheckOut</th>
				</tr>
				<tr>
					<th>Total Amount : {{total}}</th>
				</tr>
			</table>
			<a href="{% url 'cart:place_order' %}" class="btn1">Place Order</a>
			<a href="shop:home" class="btn1">Continue Shopping</a>
		</div>
	</div>
</div>

<br>

{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<center>
<div class="container">
<img src="{% static 'images/banner.png' %}" height="200px" width="1300px">
</div>


<div>
    <h5>Our Collections</h5>
</div>

<div>
    <p>Offerings such as the largest in-season product catalogue, 100% authentic products, cash on delivery and 30 day
        return policy make Myntra, the preferred shopping destination in the country. To make online shopping easier for you,
        a dedicated customer connect team is on standby to answer your queries 24x7.</p>
</div>
</center>

<!-- cards -->

<div class="container mt-3">
  <div class="row">
    {% for i in item %}
      <div class="col-4 mt-4">
        <div class="card" style="width: 18rem;">
          <img src="{{i.cimage.url}}" class="card-img-top" height="250px" width="150px" alt="..." >
          <div class="card-body">
            <center>
              <h5 class="card-title">{{i.cname}}</h5>
              <p class="card-text">{{i.cdesc}}</p>
              <a href="{% url 'shop:products' i.id %}" class="btn btn-primary">Shop Now</a>
            </center>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

ecommerce/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<br>

<img src="{% static 'images/online.jpg' %}" height="100%" width="100%">
{% endblock %}

ecommerce/templates/payment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<br>
<center>
<form action="http://127.0.0.1:8000/cart/status/{{payment.name}}" method="POST">
 {% csrf_token %}
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_IeuNEvE2rTYxQD"
    data-amount="{{payment.amount}}"
    data-currency="{{payment.currency}}"
    data-order_id="{{payment.id}}"
    data-buttontext="Pay with Razorpay"
    data-name="Mintra"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{payment.name}}"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
 </center>

<br>

 {% endblock %}

card no.: 5267 3181 8797 5449

ecommerce/templates/place_order.html
 {% extends 'base.html' %}
{% load static %}

{% block content %}

<br>

<center>
    <h5>Enter details..</h5>
</center>

<center>
<form class="container" method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label class="form-label">Phone Number</label>
      <input type="text" class="form-control" name="p">
    </div>
    <div class="mb-3">
      <label class="form-label">Delivery Address</label>
      <input type="text" class="form-control" name="a">
    </div>
    <div class="mb-3">
      <label class="form-label">Pin</label>
      <input type="text" class="form-control" name="n">
    </div>
    <div>
    <input type="submit">
    </div>
</form>
</center>

{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<br>

<div class="row">
  <img src="{{ c.cimage.url }}" height="900px;" width="100px;">
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center fw-bold">{{c.cname}}</h1>
      <p>{{c.cdesc}}</p>
    </div>
  </div>
</div>


<div class="container mt-3">
  <div class="row">
    {% for i in p %}
      <div class="col-4 mt-4">
        <div class="card" style="width: 18rem;">
          <a href="{% url 'shop:product_details' i.id %}">
            <img src="{{i.image.url}}" class="card-img-top" height="250px" width="150px" alt="..." ></a>
          <div class="card-body">
            <center>
              <h5 class="card-title">{{i.name}}</h5>
              <p class="card-text">{{i.price}}</p>
              <a href="{% url 'shop:product_details' i.id %}" class="btn btn-primary">Shop Now</a>
            </center>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

ecommerce/templates/product_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<br>

<div class="container">
        <div class="card" style="width:30%">
            <img src="{{ product.image.url }}" height='300px'>
        </div>
    <div class="col-6 p-4">
        <h2 class="fw-bold">{{product.name}}</h2><br>
        <h5 class="fw-bold">Price:{{product.price}}</h5>
        <h5>Availabe Stock:{{product.stock}}</h5>
        {% if user.is_superuser == True %}
            {% if product.stock > 0 %}
                <h3 class="text-success">Product in Stock</h3>
                <a style="text-decoration:none" href="{% url 'admin:index' %}" class="btn_1">Add Stock</a>
            {% else %}
                <h3 class="text-danger">Out of Stock</h3>
                <a style="text-decoration:none" href="{% url 'admin:index' %}" class="btn_1">Add Stock</a>
            {% endif %}
        {% else %}
            {% if product.stock > 0 %}
<!--                <button><a href="{% url 'shop:buy' product.id %}" class="btn_1">Buy now</a> </button>  <br>-->
                <button><a href="{% url 'cart:add_to_cart' product.id %}" class="btn_1">Add to Cart</a></button>
            {% else %}
                <h3 class="text-danger">Out of Stock</h3>
            {% endif %}
        {% endif %}

        <h3>Product Details<i class="fa-fa-indent"></i></h3>
        <p>{{product.desc}}</p>
    </div>
</div>

{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Register</title>
    {% endblock %}

{% block content %}

<br>
<center>
<form method="post" class="container">

    {% csrf_token %}

    <div class="mb-3">
      <label class="form-label">Usename</label>
      <input type="text" class="form-control" name="u">
    </div>
    <div class="mb-3">
      <label class="form-label">Password</label>
      <input type="password" class="form-control" name="p">
    </div>
    <div class="mb-3">
      <label class="form-label">Confirm_Password</label>
      <input type="password" class="form-control" name="c">
    </div>
    <div class="mb-3">
      <label class="form-label">First_name</label>
      <input type="text" class="form-control" name="f">
    </div>
    <div class="mb-3">
      <label class="form-label">Last_name</label>
      <input type="text" class="form-control" name="l">
    </div>
    <div class="mb-3">
      <label class="form-label">Email</label>
      <input type="email" class="form-control" name="e">
    </div>


    <div>
    <input type="submit">
    </div>

</form>
    </center>

{% endblock %}

</body>
</html>

ecommerce/templates/search_products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<title>Search</title>

<h2 class="mt-3 mb-3">Search result of {{query}}</h2>


<div class="container mt-3">
  {% if p %}
  <div class="row">
    {% for i in p %}
      <div class="col-4 mt-4">
        <div class="card" style="width: 18rem;">
          <a href="{% url 'shop:product_details' i.id %}">
            <img src="{{i.image.url}}" class="card-img-top" height="250px" width="150px" alt="..." ></a>
          <div class="card-body">
            <center>
              <h5 class="card-title">{{i.name}}</h5>
              <p class="card-text">{{i.price}}</p>
              <a href="#" class="btn btn-primary">Shop Now</a>
            </center>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  {% else %}
  <div class="row">
    <div class="col-md-12" style="">
      <h4 class="fn-bold text-center">No Search Found..</h4>
    </div>
    {% endif %}
  </div>
</div>


{% endblock %}

ecommerce/templates/status.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if status == True %}
  <link rel="stylesheet" href="{% static 'css/payment_done.css' %}">
  <div class="c">
    <div class="success">&#10004;</div>
    <h1 class="title">Payment Successful</h1>
    <div class="summary">
      <a href="{% url 'shop:home' %}" class="button">Continue Shopping</a>
    </div>
  </div>

  <h4>Payment is successfull</h4>

{% else %}

  <h4>Payment is not successfull</h4>

{% endif %}
{% endblock %}

ecommerce/templates/user_login.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Login</title>
    {% endblock %}

{% block content %}

<br>
<center>
<form method="post" class="container">

    {% csrf_token %}        <!-- security feature used by django -->

    <div class="mb-3">
      <label class="form-label">Usename</label>
      <input type="text" class="form-control" name="u">
    </div>
    <div class="mb-3">
      <label class="form-label">Password</label>
      <input type="password" class="form-control" name="p">
    </div>

    <div>
    <input type="submit">
    </div>
</form>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    </center>

{% endblock %}

</body>
</html>

ecommerce/templates/your_orders.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
<!--    <h5>Order Details</h5>-->
    <div class="container">
        <h4 class="text-center fw-bold">{{u}}'s Orders</h4>
        {% for i in customer %}
        <div class="row" style="margin-top:100px">

            <div class="col-5 p-4">
                <img src="{{i.product.image.url }}" width="200px" height="200px">
            </div>
            <div class="col-5 p-4" style="align-item:center;">
<!--                <hr class="w-25 border border-2 border-dark mx-auto">-->
                <h5>{{i.product.name}}</h5>
                <h5><b>₹:</b>{{i.product.price}}</h5>
<!--                <h5><b>Address:</b>{{i.address}}</h5>-->
<!--                <h5><b>Contact:</b>{{i.phone}}</h5>-->
<!--                <h5><b>No. of Items:</b>{{i.no_of_items}}</h5>-->
                <h5>{{i.orderd_date}}</h5>
                <h5><b>Status:</b>{{i.delivery_status}}</h5>

            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}